version: 2.1

defaults: &defaults
  environment:
    GCLOUD_PRODJECT_ID: "gcp-laboratories"
    GCLOUD_PRODJECT_REGION: "us-central1"
    TF_GCP_BUCKET: "gcp-laboratories-tf-state"
    TERRAFORM_STR: "terraform"
only-releasable: &only-releasable
  filters:
    branches:
      only:
        - master
        - develop
        - patch
non-releasable: &non-releasable
  filters:
    branches:
      ignore:
        - master
        - develop
        - patch
gcp-account-template: &gcp-account-template
  docker:
    - image: google/cloud-sdk
  steps:
    - checkout
    - run:
        name: "validate gcp service account"
        command: |
          . .circleci/definitions.sh
          echo ${GCP_SA} > ${GCLOUD_DEVOPS_SA}
          gcloud auth activate-service-account --key-file=${GCLOUD_DEVOPS_SA}
          gcloud config set project ${GCLOUD_PRODJECT_ID}
          echo "checking bucket..."
          gsutil ls gs://${TF_GCP_BUCKET}/
          echo "bucket step passed..."
terraform-template: &terraform-template
  docker:
    - image: hashicorp/terraform:light
  steps:
    - checkout
    - run:
        name: "terraform provisioning"
        command: |
          . .circleci/definitions.sh
          echo ${GCP_SA} > ${GCLOUD_DEVOPS_SA}
          cd ${TERRAFORM_STR}
          terraform init -backend-config="bucket=${TF_GCP_BUCKET}" -backend-config="prefix=${TERRAFORM_STR}"

jobs:
  test_gcp_sa_account:
    <<: *defaults
    <<: *gcp-account-template
  terraform_provisioning:
    <<: *defaults
    <<: *terraform-template

workflows:
  version: 2.1
  GCP_LABS:
    jobs:
      - test_gcp_sa_account:
        <<: *non-releasable
      - terraform_provisioning:
        <<: *non-releasable