version: 2.1

defaults: &defaults
  environment:
    TF_GCP_BUCKET: "gcp-laboratories-tf-state"
    TERRAFORM_STR: "terraform"
    TF_VAR_project_id: "gcp-laboratories"
    TF_VAR_region: "us-central1"
    TF_VAR_key: "/root/terraform-gcp-lab/credentials/credential.json"
  working_directory: /root/terraform-gcp-lab
only-releasable: &only-releasable
  filters:
    branches:
      only:
        - master
        - develop
        - patch
non-releasable: &non-releasable
  filters:
    branches:
      ignore:
        - master
        - develop
        - patch
gcp-bucket-checker-template: &gcp-bucket-checker-template
  docker:
    - image: google/cloud-sdk
  steps:
    - checkout
    - run:
        name: "validate tf state bucket "
        command: |
          echo ${GCP_SA} > ${TF_VAR_key}
          gcloud auth activate-service-account --key-file=${TF_VAR_key}
          gcloud config set project ${TF_VAR_project_id}
          echo "Checking if GCP Bucket is created..."
          gsutil ls gs://${TF_GCP_BUCKET}/
          echo "Bucket step passed!"
terraform-template: &terraform-template
  docker:
    - image: hashicorp/terraform:light
  steps:
    - checkout
    - run:
        name: "terraform provisioning"
        command: |
          echo ${GCP_SA} > ${TF_VAR_key}
          export GOOGLE_APPLICATION_CREDENTIALS=${TF_VAR_key}
          cd ${TERRAFORM_STR}
          if [[ $(git log --format=oneline -n 1 ${CIRCLE_SHA1} | grep -Eo "\[tf-destroy\]") ]]; then
            terraform init -backend-config="bucket=${TF_GCP_BUCKET}" -backend-config="prefix=${TERRAFORM_STR}"
            terraform destroy --auto-approve
          else
            terraform init -backend-config="bucket=${TF_GCP_BUCKET}" -backend-config="prefix=${TERRAFORM_STR}"
            terraform plan
            terraform apply --auto-approve
          fi
jobs:
  Is TF State Bucket Created:
    <<: *defaults
    <<: *gcp-bucket-checker-template
  Terraform Provisioning Step:
    <<: *defaults
    <<: *terraform-template

workflows:
  version: 2.1
  GCP_LABS:
    jobs:
      - test_gcp_sa_account:
          <<: *only-releasable
      - terraform_provisioning:
          <<: *only-releasable
          requires:
            - test_gcp_sa_account