version: 2.1

defaults: &defaults
  working_directory: /root/app
only-carvalhopereira: &only-carvalhopereira
  filters:
    branches:
      only:
        - carvalhopereira

pre-steps-template: &pre-steps-template
  name: "Apply GCP credentials"
  command: |
    source .circleci/cicd-definitions.sh
    echo ${DODRONES_GCP_MY_LABS_SA} > ${GCLOUD_JSON_KEY_PATH}
    gcloud auth activate-service-account --key-file=${GCLOUD_JSON_KEY_PATH}
    gcloud config set project ${GCLOUD_PROJECT_ID}

gcp-bucket-checker-template: &gcp-bucket-checker-template
  docker:
    - image: google/cloud-sdk
  steps:
    - checkout
    - run:
        <<: *pre-steps-template
    - run:
        name: "Validate tf state bucket "
        command: |
          source .circleci/cicd-definitions.sh
          echo "Checking if GCP Bucket is created..."
          echo "bucket must be named as: ${GCLOUD_PROJECT_BUCKET_NAME}"
          if [[ ! -z ${GCLOUD_PROJECT_BUCKET_NAME} ]]; then
            gsutil ls gs://${GCLOUD_PROJECT_BUCKET_NAME}/ || gsutil mb -c standard -p ${GCLOUD_PROJECT_ID} -l ${GCLOUD_PROJECT_REGION} gs://${GCLOUD_PROJECT_BUCKET_NAME}/
          else
            exit -1
          fi

jobs:
  tf_state_checker:
    <<: *defaults
    <<: *gcp-bucket-checker-template

workflows:
  version: 2.1
  GCP_LABS:
    jobs:
      - tf_state_checker:
          <<: *only-carvalhopereira
          
